# Natural Language Processing Analysis Restaurant review data is Postive or Negative.

In [45]:
import pandas as pd 
import numpy as np
Data=pd.read_csv('Restaurant_Reviews.tsv',delimiter='\t')
Data.Review

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
5         Now I am getting angry and I want my damn pho.
6                  Honeslty it didn't taste THAT fresh.)
7      The potatoes were like rubber and you could te...
8                              The fries were great too.
9                                         A great touch.
10                              Service was very prompt.
11                                    Would not go back.
12     The cashier had no care what so ever on what I...
13     I tried the Cape Cod ravoli, chicken, with cra...
14     I was disgusted because I was pretty sure that...
15     I was shocked because no signs indicate cash o...
16                                   Highly recommended.
17                Waitress was 

In [46]:
#Data.drop_duplicates(keep='first',inplace=True)
print("\n Duplicated Values: \n",Data.duplicated().any())
print("\n Describe the data of Review : \n", Data.describe())
Data=Data.iloc[:800]
print("\n Data Size : ",Data.size)


 Duplicated Values: 
 True

 Describe the data of Review : 
             Liked
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

 Data Size :  1600


In [47]:
import re # re library to clean data
import nltk # Natural Language Tool Kit 
from nltk.corpus import stopwords # remove punctuation(stop words)
from nltk.stem.porter import PorterStemmer # Steaming the words

words=[]
for word in range(0,800):
    checking=re.sub('[^a-zA-Z]'," ",Data['Review'][word])
    checking=checking.lower()
    checking=checking.split()
    ps=PorterStemmer()
    checking=[ps.stem(word) for word in checking
                      if not word in set(stopwords.words('english'))]
    checking=' '.join(checking)
    words.append(checking)
wordsN=pd.DataFrame(words)
wordsN

0
0                                       wow love place
1                                           crust good
2                                   tasti textur nasti
3    stop late may bank holiday rick steve recommen...
4                              select menu great price
5                              get angri want damn pho
6                                  honeslti tast fresh
7    potato like rubber could tell made ahead time ...
8                                            fri great
9                                          great touch
10                                       servic prompt
11                                       would go back
12        cashier care ever say still end wayyy overpr
13          tri cape cod ravoli chicken cranberri mmmm
14                      disgust pretti sure human hair
15                               shock sign indic cash
16                                    highli recommend
17                          waitress littl slow servic
18                      place worth time let alon vega
19                                                like
20                                       burritto blah
21                                           food amaz
22                                    servic also cute
23                     could care less interior beauti
24                                             perform
25               right red velvet cake ohhh stuff good
26                             never brought salad ask
27   hole wall great mexican street taco friendli s...
28   took hour get food tabl restaur food luke warm...
29                                worst salmon sashimi
..                                                 ...
770               sashimi poor qualiti soggi tasteless
771              great time famili dinner sunday night
772             food tasti say real tradit hunan style
773                                 bother slow servic
774                         flair bartend absolut amaz
775                   frozen margarita way sugari tast
776                                   good order twice
777  nutshel restaraunt smell like combin dirti fis...
778                                girlfriend veal bad
779                                      unfortun good
780                               pretti satifi experi
781               join club get awesom offer via email
782  perfect someon like beer ice cold case even co...
783  bland flavorless good way describ bare tepid meat
784                        chain fan beat place easili
785                                         nacho must
786                                          come back
787            mani word say place everyth pretti well
788  staff super nice quick even crazi crowd downto...
789               great atmospher friendli fast servic
790                    receiv pita huge lot meat thumb
791                                     food arriv meh
792  pay hot dog fri look like came kid meal wiener...
793                  classic main lobster roll fantast
794     brother law work mall ate day guess sick night
795  good go review place twice herea tribut place ...
796                 chip salsa realli good salsa fresh
797                                        place great
798                                       mediocr food
799                            get insid impress place

[800 rows x 1 columns]

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,stop_words='english',min_df=2,max_features=1000)
x=cv.fit_transform(words)
y=Data.iloc[:,1].values
print(cv,'\n',x,'\n',x.shape)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2) 



CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1000, min_df=2,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None) 
   (0, 356)	1
  (0, 279)	1
  (0, 529)	1
  (1, 199)	1
  (1, 107)	1
  (2, 312)	1
  (2, 476)	1
  (2, 471)	1
  (3, 387)	1
  (3, 262)	1
  (3, 454)	1
  (3, 279)	1
  (4, 370)	1
  (4, 202)	1
  (4, 298)	1
  (4, 418)	1
  (5, 350)	1
  (5, 111)	1
  (5, 512)	1
  (6, 188)	1
  (6, 469)	1
  (7, 254)	1
  (7, 482)	1
  (7, 473)	1
  (7, 268)	1
  :	:
  (793, 398)	1
  (794, 285)	1
  (794, 525)	1
  (794, 114)	1
  (794, 17)	1
  (794, 318)	1
  (794, 209)	1
  (794, 426)	1
  (795, 495)	1
  (795, 157)	1
  (795, 394)	1
  (795, 318)	1
  (795, 199)	1
  (795, 356)	2
  (796, 83)	1
  (796, 383)	1
  (796, 188)	1
  (796, 199)	1
  (797, 202)	1
  (7

In [49]:
xnames=cv.get_feature_names()
xnames

['absolut',
 'acknowledg',
 'actual',
 'ad',
 'ago',
 'alway',
 'amaz',
 'ambianc',
 'ambienc',
 'anoth',
 'anyon',
 'anytim',
 'appet',
 'area',
 'arriv',
 'ask',
 'assur',
 'ate',
 'atmospher',
 'attack',
 'attent',
 'attitud',
 'authent',
 'avoid',
 'away',
 'awesom',
 'babi',
 'bachi',
 'bacon',
 'bad',
 'bakeri',
 'bar',
 'bare',
 'bartend',
 'basic',
 'bathroom',
 'batter',
 'bay',
 'bean',
 'beat',
 'beauti',
 'beef',
 'beer',
 'belli',
 'best',
 'better',
 'big',
 'bisqu',
 'bit',
 'bite',
 'black',
 'bland',
 'blow',
 'boot',
 'bowl',
 'boy',
 'bread',
 'break',
 'breakfast',
 'brick',
 'bring',
 'brought',
 'brunch',
 'buffet',
 'bunch',
 'burger',
 'busi',
 'butter',
 'cafe',
 'cake',
 'came',
 'car',
 'care',
 'cashier',
 'char',
 'cheap',
 'check',
 'chees',
 'cheeseburg',
 'chef',
 'chewi',
 'chicken',
 'chines',
 'chip',
 'choos',
 'classic',
 'clean',
 'close',
 'cocktail',
 'coffe',
 'cold',
 'combin',
 'come',
 'comfort',
 'compani',
 'complaint',
 'complet',
 'consid

In [50]:
xcountname=pd.DataFrame(x.toarray(),columns=xnames)
print(xcountname.shape)
print(xcountname.head(5))

(800, 535)
   absolut  acknowledg  actual  ad  ago  alway  amaz  ambianc  ambienc  anoth  \
0        0           0       0   0    0      0     0        0        0      0   
1        0           0       0   0    0      0     0        0        0      0   
2        0           0       0   0    0      0     0        0        0      0   
3        0           0       0   0    0      0     0        0        0      0   
4        0           0       0   0    0      0     0        0        0      0   

   ...   work  world  worst  worth  wow  wrap  wrong  year  yummi  zero  
0  ...      0      0      0      0    1     0      0     0      0     0  
1  ...      0      0      0      0    0     0      0     0      0     0  
2  ...      0      0      0      0    0     0      0     0      0     0  
3  ...      0      0      0      0    0     0      0     0      0     0  
4  ...      0      0      0      0    0     0      0     0      0     0  

[5 rows x 535 columns]


In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

LR=LogisticRegression()
print(LR.fit(x_train,y_train))

DT=DecisionTreeClassifier()
print(DT.fit(x_train,y_train))

SVC=SVC()
print(SVC.fit(x_train,y_train))

RF=RandomForestClassifier()
print(RF.fit(x_train,y_train))

C:\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
    

In [52]:
#Prediction Different Algorithms

LRPrediction= LR.predict(x_test)
SVCPrediction=SVC.predict(x_test)
RFPrediction=RF.predict(x_test)
DTPrediction=DT.predict(x_test)

print(" Confusion Matrix of Different Algorithm ")
print("\n Logistic Regression : \n", accuracy_score(LRPrediction, y_test))
print("\n Support Vector Machine : \n", accuracy_score(SVCPrediction,y_test))
print('\n Random Forest : \n', accuracy_score(RFPrediction,y_test))
print('\n Decision Tree : \n',accuracy_score(DTPrediction,y_test))


# Confusion Matrix
print(" Confusion Matrix of Different Algorithms ")
print("\n Logistic Regression : \n", confusion_matrix(LRPrediction, y_test))
print("\n Support Vector Machine : \n", confusion_matrix(SVCPrediction,y_test))
print('\n Random Forest : \n', confusion_matrix(RFPrediction,y_test))
print('\n Decision Tree : \n',confusion_matrix(DTPrediction,y_test))

# classification Report
print("  Classification Report of Different Algorithms ")
print("\n Logistic Regression : \n", classification_report(LRPrediction, y_test))
print("\n Support Vector Machine : \n", classification_report(SVCPrediction,y_test))
print('\n Random Forest : \n', classification_report(RFPrediction,y_test))
print('\n Decision Tree : \n',classification_report(DTPrediction,y_test))


 Confusion Matrix of Different Algorithm 

 Logistic Regression : 
 0.725

 Support Vector Machine : 
 0.58125

 Random Forest : 
 0.70625

 Decision Tree : 
 0.7125
 Confusion Matrix of Different Algorithms 

 Logistic Regression : 
 [[44 21]
 [23 72]]

 Support Vector Machine : 
 [[ 0  0]
 [67 93]]

 Random Forest : 
 [[47 27]
 [20 66]]

 Decision Tree : 
 [[39 18]
 [28 75]]
  Classification Report of Different Algorithms 

 Logistic Regression : 
               precision    recall  f1-score   support

           0       0.66      0.68      0.67        65
           1       0.77      0.76      0.77        95

   micro avg       0.72      0.72      0.73       160
   macro avg       0.72      0.72      0.72       160
weighted avg       0.73      0.72      0.73       160


 Support Vector Machine : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.58      0.74       160

   micro avg       0.58  

C:\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [58]:
def review_prediction(review):
    new_corpus = []
    review = re.sub('[^a-zA-Z]', ' ' ,review)
    #converting all characters to lowercase
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
   #loop for stemming each word in string array at ith row
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    #rejoin all string array elements to create back into a string
    review = ' '.join(review)
    #append each string to create array of clean text
    words.append(review)
    count_vect = CountVectorizer(lowercase=True,stop_words='english',min_df=2,max_features = 10000)
    x_count_vect = count_vect.fit_transform(words + new_corpus).toarray()
    x = x_count_vect[-1].reshape(1, -1)
    prediction = LR.predict(x)
    if prediction == 1:
        return "Positive Review"
    else:
        return "Negative Review"

In [60]:
# Positive Review
print(review_prediction(input()))


feeling good to live in Mumbai
Positive Review


In [62]:
# Negaive_Review
print(review_prediction(input()))

I feel Worst journey 
Negative Review


In [ ]:
print(review_prediction(input()))
